version: '3'
services: 
  mui-server:
    image: registry.cn-hangzhou.aliyuncs.com/zfly/muisample:latest
    container_name: mui-server
    networks:
        - mui-network
    ports:
      - 5150:5150
    links:
      - mui-etcd
    deploy:
      replicas: 6

  mui-etcd:
    image: quay.io/coreos/etcd:v2.3.7
    container_name: mui-etcd
    expose:
      - 2379

networks:
  mui-network:
    driver: overlay